### ISSUE TITLE
Doing [p]dc throws error

### ISSUE THREAD

**Issue by fakesmile9704** [Drapersniper/PyLav#254] opened 2023-07-21 20:03 UTC
**Describe the bug**
the music is playing all of a sudden it stopped but when i did [p]queue it says there is no songs so i did [p]dc and it thow an error

**To Reproduce**
 - add a playlist of 200 songs 
 - while playing it stopped 
 - try dc 

**Expected behavior**
it should dc

**Screenshots**
![image](https://github.com/PyLav/Red-Cogs/assets/69390477/afd043dc-d076-4255-8faf-880d46562e3d)

**Additional context**
```Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/red/cogs/CogManager/cogs/audio/hybrid_commands.py", line 469, in command_disconnect
    await context.player.disconnect(requester=context.author)
  File "{HOME}/red/cogs/Downloader/lib/pylav/players/player.py", line 1731, in disconnect
    self.player_manager.client.scheduler.remove_job(job_id=f"{self.bot.user.id}-{self.guild.id}-auto_dc_task")
  File "{HOME}/red/cogs/Downloader/lib/apscheduler/schedulers/base.py", line 625, in remove_job
    raise JobLookupError(job_id)
apscheduler.jobstores.base.JobLookupError: 'No job by the id of 1015834434513158184-1131992119180017684-auto_dc_task was found'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "{HOME}/redenv/lib/python3.11/site-packages/discord/ext/commands/core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: JobLookupError: 'No job by the id of 1015834434513158184-1131992119180017684-auto_dc_task was found'```

**Comment by Drapersniper** [comment] 2023-07-21 20:55
> To Reproduce
> Steps to reproduce the behavior:
> 
> add a playlist of 200 songs
> while playing it stopped
> try dc

Are you saying this is 100% reproducible with these steps because I cannot reproduce it

**Comment by fakesmile9704** [comment] 2023-07-22 07:14
> 

I dont think it is 100% reproducible cause i tried it again and again and i only triggered it 2 times

**Comment by Drapersniper** [comment] 2023-10-08 12:09
I believe this is now resolved in latest release, if it still reproduces feel free to reopen

**Closed as completed by Drapersniper** 2023-10-08 12:09 UTC
Labels: needs more info
